# Generated by Django 4.1.7 on 2023-03-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qtd_telas',
            new_name='Qtd_tela',
        ),
        migrations.RenameModel(
            old_name='Servidores',
            new_name='Servidor',
        ),
    ]
