# Generated by Django 4.1.7 on 2023-04-05 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_data_adesao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de cancelamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 4, 5), verbose_name='Data de adesão'),
        ),
    ]
