# Generated by Django 4.1.7 on 2023-04-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.plano'),
        ),
    ]
