# Generated by Django 4.1.7 on 2023-04-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_plano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qtd_tela',
            old_name='nome',
            new_name='telas',
        ),
    ]
