# Generated by Django 4.1.7 on 2023-04-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_qtd_tela_telas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.qtd_tela'),
        ),
    ]
