# Generated by Django 4.1.7 on 2023-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cliente_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_pagamento',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
