# Generated by Django 4.1.7 on 2023-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cliente_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultimo_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Último pagamento realizado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_pagamento',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
