# Generated by Django 4.1.7 on 2023-04-07 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_ultimo_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 4, 7), verbose_name='Data de adesão'),
        ),
    ]
