# Generated by Django 4.1.7 on 2023-04-07 21:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cliente_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', unique=True),
        ),
    ]
