# Generated by Django 4.1.7 on 2023-04-07 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 21, 54, 48, 221009, tzinfo=datetime.timezone.utc), verbose_name='Data de adesão'),
        ),
    ]
