# Generated by Django 4.1.7 on 2023-04-07 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cliente_data_adesao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 21, 56, 11, 280012, tzinfo=datetime.timezone.utc), verbose_name='Data de adesão'),
        ),
    ]
