# Generated by Django 4.1.7 on 2023-04-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cliente_data_adesao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qtd_tela',
            options={'verbose_name_plural': 'Quantidade de telas'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'verbose_name_plural': 'Servidores'},
        ),
        migrations.AlterModelOptions(
            name='tipos_pgto',
            options={'verbose_name': 'Tipo de pagamento', 'verbose_name_plural': 'Tipos de pagamentos'},
        ),
    ]
