# Generated by Django 4.1.7 on 2023-04-07 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_qtd_tela_options_alter_servidor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de adesão'),
        ),
    ]
