# Generated by Django 4.1.7 on 2023-04-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagamento',
            new_name='Mensalidade',
        ),
    ]
