# Generated by Django 4.1.7 on 2023-04-08 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_pagamento_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 4, 7), verbose_name='Data de adesão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.plano'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.qtd_tela'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do plano'),
        ),
        migrations.AlterField(
            model_name='qtd_tela',
            name='telas',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Quantidade de telas'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tipos_pgto',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
