# Generated by Django 4.1.7 on 2023-04-08 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_dispositivo_modelo_mensalidade_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='dt_pagamento',
            field=models.DateField(default=None, verbose_name='Data de pagamento'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2023, 5, 7), verbose_name='Data de vencimento'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='pgto',
            field=models.BooleanField(default=False),
        ),
    ]
