# Generated by Django 4.1.7 on 2023-04-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_mensalidade_dt_pagamento_mensalidade_dt_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_pagamento',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de pagamento'),
        ),
    ]
