# Generated by Django 4.1.7 on 2023-04-11 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_cliente_data_adesao_alter_mensalidade_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 4, 11), verbose_name='Data de adesão'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2023, 5, 11), verbose_name='Data de vencimento'),
        ),
    ]
