# Generated by Django 4.1.7 on 2023-04-17 01:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_mensalidade_cancelado_alter_cliente_data_adesao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dispositivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.dispositivo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sistema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.sistema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 4, 16), verbose_name='Data de adesão'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2023, 5, 16), verbose_name='Data de vencimento'),
        ),
    ]
