# Generated by Django 4.1.7 on 2023-04-17 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_cliente_dispositivo_cliente_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 4, 17), verbose_name='Data de adesão'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2023, 5, 17), verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='tipos_pgto',
            name='nome',
            field=models.CharField(choices=[('PIX', 'PIX'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Boleto', 'Boleto')], default='PIX', max_length=255, unique=True),
        ),
    ]
